version: "3.7"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui # latest
    container_name: swagger-ui
    depends_on:
      - logging-api
      - products-api
      - invoicing-api
      - orders-api
    environment:
      - URLS=[{url:"/app/logging-api/specification/openapi.yaml",name:"Logging API"},{url:"/app/products-api/specification/openapi.yaml",name:"Products API"},{url:"/app/invoicing-api/specification/openapi.yaml",name:"Invoicing API"},{url:"/app/orders-api/specification/openapi.json",name:"Orders API"}]
    ports:
      - 80:8080
    volumes:
      - ./app:/usr/share/nginx/html/app

  logging-api:
    image: maanuelmm/prism # custom image to avoid two bugs in two different versions.
    init: true
    command: mock -d -h 0.0.0.0 "/app/openapi.yaml"
    restart: on-failure # incredibly unreliable
    ports:
      - 4010:4010
    volumes:
      - ./app/logging-api/specification:/app

  products-api:
    image: maanuelmm/prism # custom image to avoid two bugs in two different versions.
    init: true
    command: mock -d -h 0.0.0.0 "/app/openapi.yaml"
    restart: on-failure # incredibly unreliable
    ports:
      - 4011:4010
    volumes:
      - ./app/products-api/specification:/app

  invoicing-api:
    image: maanuelmm/prism # custom image to avoid two bugs in two different versions.
    init: true
    command: mock -d -h 0.0.0.0 "/app/openapi.yaml"
    restart: on-failure # incredibly unreliable
    ports:
      - 4012:4010
    volumes:
      - ./app/invoicing-api/specification:/app

  orders-api:
    image: maanuelmm/prism # custom image to avoid two bugs in two different versions.
    init: true
    command: mock -d -h 0.0.0.0 "/app/openapi.json"
    restart: on-failure # incredibly unreliable
    ports:
      - 4013:4010
    volumes:
      - ./app/orders-api/specification:/app
